### PR TITLE
Added navbar for login

### PR DESCRIPTION
**Pull request by Nilkamal**

### CODE REVIEW

**Comment by ArnasDickus** [comment]
Okay I look into it.
Trello task
https://trello.com/c/EwETdqCW/56-create-login-navbar-and-logout-navbar-from-provided-mockups

**Comment by ArnasDickus** [comment]
Good work for adding a pull request. Navbar is starting to look good. Here's the problems I encountered. Also I added optional tasks if you up to it.
Okay I see a 2 problems and 3 improvements.
1) Your navbar don't have mobile menu. As you shrinking the view the hamburger button should appear. And menu be hidden. If I click on hamburger menu should appear from right side. To know exact size when menu should appear try to make it look good on login page.
2) header now stands at his own element. Navbar should be on right side with the element, login menu should be next to navbar not below.
menu-with-navbar

3) horizontal lines should look closer to design.
4) Login and sign up page buttons should look closer to design Look at login.js button design.
5) After Team members there should be a new line look in design.

Optional:
In login.js file former contributor forgot to change class to className.
Change title to Mappypals. In public index.html instead of React App.

Apart from that good work. Started with not the easiest task.

**Comment by ArnasDickus** [comment]
Hey @SamirJouni Why did you merged and revert changes?

**Comment by SamirJouni** [comment]
Sorry, merged it by mistake, reverted it. Please reopen the pull request.

**Comment by ArnasDickus** [comment]
@SamirJouni I reoponed pull request but now our original contributor is not showing 
https://github.com/zero-to-mastery/mappypals/pull/37
I decided to just close request and ask contributor to open a new one.

**Pull request merged**
