### PR TITLE
Profile settings

### PR DESCRIPTION
**Pull request by ArnasDickus**
[Trello task](https://trello.com/c/WzhEq5VR/126-profile-settings-mockup)

Finished Profile settings. 
Here are my current concerns:
1) Navbar menu is not operational, because we don't have email and password page.
2) change picture selects picture but does not actually update it. Because from my understanding the same way with forms you need to verify in front-end and back-end if the picture is in a correct format.
  2.1) For front-end verify and inform the user, that format is not supported.
  2.2) Back-end verify for security purposes before adding to DB.
3) I don't like the Interest section. Because if for example 3 users like Runescape:
  3.1) First user adds interest Runescape
  3.2) the Second user adds interest runescape
  3.3) The third user adds Playing Runescape. None of the interest matches. 

4) I suggest two options:
    4.1) create or find a JSON file with all the interests. So that user types a few letters dropdown appears and can select an interest, for example, playing video games, etc.
    4.2) Improve the Interest section. Add Movie interest and use 
[movie api](https://www.themoviedb.org/documentation/api). And video game interest and use another API. Hobbies, etc.

5) Used module.css so that my css won't spill to other files. Copied. input design from form.js in ProfileSettings.module.css. Didn't import any css from other files.
6) The website is responsive, let me know if I need to adjust something.
7) Also, what does the cancel button supposed to do? I suggest removing it.

### CODE REVIEW

**Review by mubarakshow — COMMENTED** [review]
1. Image Picker
- should only allow users to pick image files. it currently allows all types of files.
- please change the thumbnail to dummy image. 
- the image should be linked to a user's profile which required backend work. 

2. Uncomfortably wide spacing between firstname & lastname.
- im sure this is from @thijsnijhof mockup, but please reduce the space by a few pixels. 

3. Can we remove the cancel button @thijsnijhof ? 
- for me, yes we should remove it. It serves no purpose.

4. I'm unable to test for when a user is logged in because for some weird reasons i'm still not able to Singup/Login into this app. 
- Anyways, when a user is logged in, their details should automatically be displayed in their profile. Has that been implemented @ArnasDickus ?? 

Other than these, great work.
We'll need to hook this to the backend once completed.

**Comment by ArnasDickus** [comment]
@mubarakshow 
So here are my fixes:
1) Regarding images, I already had front-end verification. But I also added so that users can't add svg or gif files. Also what kind of dummy image I'm supposed to be using. I already used the image.
2) I don't know how to decrease space between firstName and lastName. Using grids, they are equally taking space in the form. Do you know how to do it using the grid, or a flexbox?
3) Decreased form size on the desktop.

I don't know how to implement back-end stuff.
When a user logged in details automatically should display anyways. I need some pointers before doing that. Or add it into another task

**Comment by ArnasDickus** [comment]
Alright, new fixes:
1) The settings menu is operational.
2) Decreased space between first name and last name by 50px.

Regarding your question: 
When a user is logged in, their details should automatically be displayed in their profile. I don't know how to do that exactly. I suggest creating a new task for that. And leave it to back-enders or at least have some discussion on how to do that.

My concerns:
1) What your views on user typing Interests manually?

**Comment by mubarakshow** [comment]
Looks good to me except there are some minor bugs which can be addressed later 👍

**Pull request merged**
