### PR TITLE
Hopefully this works.

### PR DESCRIPTION
**Pull request by nottoobright**
Okay, now this is the v1 working version for all of Auth. Signup, login, forgot and reset, confirm email, etc.

### CODE REVIEW

**Comment by mubarakshow** [comment]
@nottoobright I know it was a frustrating task but can we please have a more descriptive naming of our PRs. It'll help others know what exactly they're reviewing. 

Thanks.

**Comment by nottoobright** [comment]
While I submitted this PR I was talking on DM with Arnas so he was actively reviewing it until he got busy.

Anyway, this is the last working version of the app I had locally. There were some problems caused due to splitting and this solves them. Still a lot of edits remaining but I haven't committed them to avoid conflicts as of now.

**Comment by mubarakshow** [comment]
@nottoobright please, look at the failed Travis check and try to fix it.

**Comment by nottoobright** [comment]
@mubarakshow - It's fixed. Have you reviewed this PR yet because I'm refraining from adding more commits as it might become too big of PR to review then?

**Comment by mubarakshow** [comment]
@nottoobright great! 

I haven't reviewed your latest commits as i'm away from my main machine. I'll do so when i get hold of my laptop.

**Comment by nottoobright** [comment]
Okay. These commits are in sync with the back-end PR I have opened as well so to test, make sure to clone both PR and test together or it might not work.

**Comment by ArnasDickus** [comment]
Reviewing pull request.
Please note that  this pull request needs to be reviewed with back-end pull request together.
https://github.com/zero-to-mastery/mappypals_backend/pull/3

**Review by ArnasDickus — COMMENTED** [review]
So here's my review:
Registration works well.
Register forms still has it's problems:
1) Allows you to register with weak password.
But this pull request is already too big. These things can be fixed in another pull request.

After registration. I didn't get a letter to my email to confirm anything. Tried 2 gmail accounts. 
siftheat@gmail.com
1arnasdickus1@gmail.com
Not sure why it didn't send anything.
After I modified my account mongo db table active from false to true. Login works. So the only issue is why I didn't get an email sent.

**Comment by ArnasDickus** [comment]
So after talking with  @nottoobright turns out. I needed to use fake emails for it to work. Not real ones due to cost issue. Using ethereal everything seems to work.
Register - works add's items to mongo database.
Login - works if manually change in mongoDB active from false to true.
Reset password - works using Etheral email.

**Pull request merged**
