### PR TITLE
Create Login Navbar from provided mockups

### PR DESCRIPTION
**Pull request by ArnasDickus**
My first draft for navbar. I tested on login mostly.

I encountered a few problems so here it goes:
1) I'am not sure how mobile design should look like from @thijsnijhof 
  1.1) If you look at his design 
https://trello.com/c/Z39k3yFt/42-login-navbar-and-logout-navbar-mockups 
It has a hamburger icon. If I click on hamburger icon the menu should appear. But mobile menu from my understanding is way too big for mobile phones. Should I just try to decrease it's width when on mobile?

2)  Hamburger icon location.
  2.1) From my understanding hamburger icon is relative to navbar. But at 768px I would hide navbar using display: none. And hamburger icon won't be relative to navbar anymore. So how can I make hamburger icon always relative to navbar, if I'm going to hide it?

3) I also not sure what to do with map and how to add navbar to the map.

Also thanks to @Nilkamal for working on this project. I was able to make use of his already written code instead of creating navbar from scratch.
Task:
https://trello.com/c/EwETdqCW/56-create-login-navbar-from-provided-mockups

### CODE REVIEW

**Comment by ArnasDickus** [comment]
Alright I talked with Thjis privately. And he answered all my questions. Going to create Draft 2

**Comment by sciortinomrc** [comment]
@ArnasDickus please notify when you push the next commit

**Comment by ArnasDickus** [comment]
Hello @sciortinomrc  I created another draft. This is one is working version but it does not look very good. According to @thijsnijhof I should be aiming for here https://www.ladeutmode.nl/. However In react it's proven to be more difficult when expected. I'm a little stumped. Going to watch some react navbar tutorials.

1) I have to use float right to put element to right side. And don't have div with 100%  width. So I can't on click cover specific screen value like 30%. 
2) I have no idea how to create dark overlay on hamburger toggle probably in app.js file somehow. Also do we need a dark overlay if menu is activated on phones?
3) Also navbar have to be position absolute, in order for map to work. But in return it creates a white space at right side. Interestingly If I quickly put my phone in landscape mode and back. The menu would jump to center.  

So yeah I'am going to watch some react navbar tutorials. And if I don't find an answer someone else could take over this tasks. Or you could just push it now, and we fixed it properly later.

**Comment by sciortinomrc** [comment]
something that seems to work is:
-App.js change order of the components so you have <Navbar /> as the last component of <React.Fragment />
-Navbar.css  add this lines to header

`	position: absolute;
	top:0px;
	height:100vh;`

when it comes to media query I guess it will have to be DOM manipulation

**Comment by ArnasDickus** [comment]
So I watched a few navbar react tutorials. And I'm still out of ideas. I don't think it's very efficient to chat about how to fix my code. I think it would be faster for me to leave this task and allow anyone else to finish using my existing code, or starting from scratch.
Trello task https://trello.com/c/EwETdqCW/56-create-login-navbar-from-provided-mockups

**Pull request closed without merging**
