### PR TITLE
Background delete from #root and put again on the right pages

### PR DESCRIPTION
**Pull request by Melissendra**
Please take  look to what i did for the background and tell me if i must modify something else.

### CODE REVIEW

**Comment by mubarakshow** [comment]
@Melissendra Great work! I'll merge your PR once we've merged the [new Navbar PR](https://github.com/zero-to-mastery/mappypals/pull/61)

**Comment by ArnasDickus** [comment]
Hello @Melissendra I can't merge this pull request. Because you want to merge it to master branch. It should be merged to dev branch. Open another pull request to dev branch.

**Comment by mubarakshow** [comment]
@ArnasDickus nice catch!

**Comment by ArnasDickus** [comment]
@mubarakshow In Admin@Mappypals. I have created and pinned message on how to review pull request might prove useful to you.

**Comment by Melissendra** [comment]
So what do I have to do?

**Comment by ArnasDickus** [comment]
@Melissendra Add a pull request exactly the same way. But instead of putting base to master branch. Put it to dev branch.
git-ignore-3

**Comment by Melissendra** [comment]
Ok thanks. I’ll do it tomorrow morning!

**Pull request closed without merging**
