### PR TITLE
single npm start for frontend and server

### PR DESCRIPTION
**Pull request by sciortinomrc**
https://trello.com/c/8SBwqLax/26-create-script-to-start-both-servers

### CODE REVIEW

**Comment by mubarakshow** [comment]
npm err

I've tested your PR, it runs fine but there were some npm errors. can you look into it and see if its okay to merge? @sciortinomrc @Dan-Y-Ko

**Comment by sciortinomrc** [comment]
You need to npm install the server folder

**Comment by mubarakshow** [comment]
> You need to npm install the server folder

got it

**Comment by mubarakshow** [comment]
server err

I get this error from the backend when i visit the localhost:3001  
is that suppose to be? @sciortinomrc

**Comment by sciortinomrc** [comment]
Let me check it and I'll come back to you in a few hours

**Comment by sciortinomrc** [comment]
ok. there's an incomplete command "client." I left probably while I was trying something and just forgot it was there. I'll correct it and you can try again

**Comment by mubarakshow** [comment]
All good now :+1:

**Pull request merged**
