### PR TITLE
Add prettier and deleted ResetPasswordEmail files

### PR DESCRIPTION
**Pull request by fuckupc**
https://trello.com/c/aZ81Zut9/115-implement-prettier-remove-resetpasswordemail

### CODE REVIEW

**Comment by belyas** [comment]
I think you need eslint prettier plugin to work along with eslint, in package.json file you'll need to add something like:
```
"eslintConfig": {
    "extends": "react-app",
    "plugins": ["prettier"],
    "rules": {
      "prettier/prettier": "error"
    }
  }
```
Of course you need to install `prettier` and `eslint-plugin-prettier` as dev depenendencies.
I see that you have already created `.prettierrc` file which is good, the last trick is to turn on the format on save for visual studio code in setting area, like this we can have instant formatting on saving the code.

**Comment by mubarakshow** [comment]
@fuckupc this PR failed Travis check. Please review it and commit a fix.

**Comment by ArnasDickus** [comment]
@mubarakshow @fuckupc Hello, so the problem with Travis test is most likely because I committed bad package-lock.json [Full explanation](https://trello.com/c/TnwPRKAS/118-fix-travis-test-error).  Because of it Dev branch do not pass Travis test [here](https://travis-ci.org/zero-to-mastery/mappypals/branches). 

So to fix it 2 issues with one pull request. I suggest this:
1) Delete package-lock.json file.
2) Run npm install so that package-lock.json file would appear again.
3) Commit changes to this pull request. 

If Travis test still do not pass.
1) Take package-lock.json from [here](https://github.com/mubarakshow/mappypals/blob/about-page/package-lock.json).
2) Put that package-lock.json into your project.
3) Commit changes. When I think Travis test should pass

**Comment by fuckupc** [comment]
> @mubarakshow @fuckupc Hello, so the problem with Travis test is most likely because I committed bad package-lock.json [Full explanation](https://trello.com/c/TnwPRKAS/118-fix-travis-test-error). Because of it Dev branch do not pass Travis test [here](https://travis-ci.org/zero-to-mastery/mappypals/branches).
> 
> So to fix it 2 issues with one pull request. I suggest this:
> 
> 1. Delete package-lock.json file.
> 2. Run npm install so that package-lock.json file would appear again.
> 3. Commit changes to this pull request.
> 
> If Travis test still do not pass.
> 
> 1. Take package-lock.json from [here](https://github.com/mubarakshow/mappypals/blob/about-page/package-lock.json).
> 2. Put that package-lock.json into your project.
> 3. Commit changes. When I think Travis test should pass

**Comment by ArnasDickus** [comment]
So I didn't found any further problems. Good work. I'm merging it.

**Pull request merged**
