### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by sciortinomrc**
https://trello.com/c/6TU3t2xu/73-hovers-active-on-navbar
https://trello.com/c/1MqSoLyW/84-create-navbar-logged-in-from-provided-mockup
https://trello.com/c/Z39k3yFt/42-login-navbar-and-logout-navbar-mockups

Task not 100% completed. Still need to work on responsive media queries.

### CODE REVIEW

**Review by ArnasDickus — COMMENTED** [review]
Here's my review:
Technically you are working on the wrong task. 
This is UI/UX task that should stay on finished design items. 
https://trello.com/c/Z39k3yFt/42-login-navbar-and-logout-navbar-mockups

Your task is here in Tasks area.
https://trello.com/c/EwETdqCW/56-create-login-navbar-and-logout-from-provided-mockups

Here the problems I saw:
1) debug.log Is this supposed to be in the project? You might want to add it to .gitignore?
2) When selecting Login or Sign up should hover over button instead of item-wrapper. Maybe disable hovering on last child.
3) Mobile menu hamburger icon I would move a little so that it won't be right on right side top corner.
On mobile I don't see hr lines.
4) I would add hamburger icon at 1090 width. Based on login. Because menu is too big to use solely on  phone on navbar.
5) If I click on left side corner of for example Team, navbar would disappear. Also on login form clicking on sign up. navbar also would disappear. It would reappear after refreshing website.

**Comment by sciortinomrc** [comment]
@ArnasDickus  PR updated.
1. debug.log delete - it's probably been created by npm
2. fixed and add scale 1.01
3. hamburger moved 10px from the corner.
5. fixed - the feature was developed for small screens but I just had forgotten to give a condition for the full screen version.

4. I did not quite get what you meant by that

**Review by ArnasDickus — COMMENTED** [review]
Alright I see you fixed most bugs. And that bug you didn't understood is also fixed. I encountered only 2 problems. On tablet menu also look good.

On Mobile Android I can't see top icon. Or scroll up to see icon. I can scroll down. Also hr lines disappeared.
Screenshot_20190505-165849

Optional fix. I can click Login button outside of login button at left side and signup buttons. It should probably be only be able to click on button only. But It's not that big deal.
I can select outside button

**Comment by sciortinomrc** [comment]
Note that I did not work on any media query yet... The only fix to do now is on the icon size to make everything fit on every device

**Comment by sciortinomrc** [comment]
Responsive CSS completed. Should be ready to merge

**Comment by mubarakshow** [comment]
@sciortinomrc 
I've reviewed your PR. The navbar seems to be placed above the pages so when pages load some parts are covered by the navbar. Whereas the navbar should be positioned separately.

navbar-design

Suggested fix: you can add the pages and navbar in a single div then use CSS Grid to position them.
``` jsx
<div class='container'>
   <Pages />
   <Navbar />
</div>
``` 
``` css
.container {
   display: grid;
   grid-template-column: 80% 20%; 
}
```
The css is just an example, you can find the numbers that would work perfectly. :)

**Comment by sciortinomrc** [comment]
@mubarakshow I've tried some fixes but it does not seem to work properly. I guess it's just the way mapbox-gl works.

Also I am having some problems on device rotation.

**Comment by sciortinomrc** [comment]
all good to go!
last commit fixed css layout full screen up to 900px.. then hamburger kicks in and sidebar overlaps on click

plus landscape errors I was having are also fixed.

Please review but should be ready to merge now

**Comment by ArnasDickus** [comment]
Okay I going to review it your updated version

**Review by ArnasDickus — COMMENTED** [review]
Okay so here's my review:
1) Mappypals menu I would remove some top white space. Mappypals icon should be where my line is more or less according to design.
navbar-icon-on-top

2) Improve text. Mappypals text was  color #E03BFB  possibly the same color I forgot my password link. Also Team, and About remove font-weight: bold according to design.
3) Copyright - Team members - ZTM URL, should be a lower, and not on the same line. According to design. 

On my Phone.
1) On login page. If I click on hamburger icon. And try to scroll down, navbar menu disappears. If I move up menu appears.
2) On portrait menu. Menu would look bad.
Screenshot_20190508-112236

3) On portrait menu if I click on hamburger icon. Application would crash. Also note, that application would only crash if I click on hamburger icon on normal view. Go to portrait mode and click on hamburger menu again.
Screenshot_20190508-112027

I'm impressed how many things can go wrong if menu is on the right side.
Also if this landscape business would prove more problem than it's worth it's possible to just disable the menu.
https://stackoverflow.com/questions/43634583/prevent-landscape-orientation-mobile-website

**Comment by sciortinomrc** [comment]
It's also impressive how many things can go wrong from one device to the other.. I have literally tested it in any Chrome test device and it was fine. 
I'll have a look today

**Comment by mubarakshow** [comment]
@sciortinomrc @ArnasDickus I'll be addressing 2 things in this review.

1. **Landscape mode** - I believe this application is more convenient in Portrait mode rather than Landscape mode. Based on my observations, most people use their phone in Portrait, except when watching a video. Also, have you tried using Twitter in Landscape mode, its works fine but the experience is not the best. 

- **_Suggestion_**: We can disable Landscape, for now.

2. **Navbar sticky** - The navbar should be fixed and non-scrollable. Meaning it shouldn't scroll with the rest of the page. Let's take a look at the about page for example: 
navbar-scroll

- **_Suggestion_**: Make the navbar sticky, and the content of the page scrollable when needed.

**Comment by sciortinomrc** [comment]
Just committed some changes. 
Not all error are fixed due to limited time but most of them are ok now.
Also login/logout navbar is implemented in this commit.
please let me know if there are any other errors/bugs  (i know the error @mubarakshow pointed out is still there and I have to figure out what's causing it and I'll do it when I can spend some solid time on it)

**Comment by mubarakshow** [comment]
@sciortinomrc 
The error below pops up when you click on the **Login** on the Navbar.  
onLogin err

Navbar is now sticky. Great work!

**Comment by sciortinomrc** [comment]
Yes I know. I have commented the onLogin const and changed the values to try the LoggedIn loggedout navbar just needs to be uncommented

**Comment by sciortinomrc** [comment]
Ok task completed.

Please review and if all good from your side ready to merge

**Comment by ArnasDickus** [comment]
I try to review it.

**Review by ArnasDickus — COMMENTED** [review]
Small typo:
So since we agreed in admin chat that Team page is about and about is contact page. Shouldn't we?
1) Rename Team page to About Us
2) Rename About to Contact Us.

On Mobile:
1) Found a bug. Navbar menu disappears.
   1.1) On dashboard opening a menu clicking on Team page AKA about page. Clicking on navbar again would make menu disappear. 
Screenshot_20190513-123731
   1.2) The bug happens only in Team Page.

**Comment by sciortinomrc** [comment]
It does not disappear. 
The bug is into the about page stying as there's no overflow handling but that page will be replaced so all good. In fact if you scroll at the end of the page you will see it there.

If you try to select <div class="sc-htpNat cuQcrA" style="
"> and add inline style overflow: hidden the bug will not present itself

**Comment by ArnasDickus** [comment]
All good I'm merging it.

**Pull request merged**
