### PR TITLE
Dashboard invite

### PR DESCRIPTION
**Pull request by ArnasDickus**
So here's my first draft. Working invitation form.

Note: I used prettier on entire code base. So it changed About.css, About.js TeamCard.js,  team-data.js, I didn't personally changed those files.

1) Added working AddFriendForm.js, InvitationSend.js.
2) Had to use in AddFriendForm.css a few !important to tags to override Login, component and in InvitationSend.css to override Form component. We should probably fix those components by tagging instead of elements to classes. So that I wouldn't need to use !important tag.

3) On Mobile trying to type anything opens navbar for some reason. I think it's a bug on navbar side. Not going to fix it on this pull request.
4) Cancelling Invitation send form. Will give you warning Form submission canceled because the form is not connected. You can fix it in InvitationSent with hideForm function. I left it because this form does not submit anything anyways.
5) Deleted a lot of items from map.js
   5.1) Removed everything associated with popup. Because Marco told me that it's not neede
  5.2) Removed this.addNewRef - because I didn't liked this kinda of code
` this.addNewRef.current._reactInternalFiber.child.alternate.stateNode.children[0].style.border =	
 '2px solid red';` One change in structure and this is no longer working.
And a few more changes.

### CODE REVIEW

**Review by mubarakshow — COMMENTED** [review]
@ArnasDickus there are few issues: 
1. When the map load, the **big blue pin** that indicates your current location is no longer there.
2. After clicking on the **send invite** button, the pin does not stay on the map.
3. I can't add a second pin to the map - because it still acts as the first pin has not been dropped, so when you click on the map to add a second pin, the first one moves to the clicked position. 
4. On hover, user detail does not pop up. 
5. The background-image on login & signup has disappeared.

**Comment by ArnasDickus** [comment]
@mubarakshow The second draft, fixed all issues. Except for issue 4. 

I have a few questions regarding on hover, user detail does not pop up.
1) On mobile, it's going to be on click right, because hover does not exist on mobile?
2) I can't figure out how to display values right next to a particular pin. Clicking on a pin will print data to console.log. The problem is: how to display values near that pin? If you have any idea I can try them. If not we could create another task for hover issue, because this pull request is already changed a lot.

**Comment by mubarakshow** [comment]
@ArnasDickus everything looks fine except for the **user details popup** you mentioned.
Here's the flow of the map: 

_Web_: 
- OnHover: user details should popup, and disappear when not onHover anymore.
- OnClick: should direct to the user's full profile page.
 
_Mobile_: 
- OnHover: not available 
- OnClick: should direct to the user's full profile page

I'll merge this PR but the popup issue needs to be addressed urgently because it enhances our UX

**Comment by ArnasDickus** [comment]
@mubarakshow Hovering on details, where do the details appear? Near clicked pin? Or somewhere in a static specific place?

**Comment by ArnasDickus** [comment]
@mubarakshow So since you approved my code. I'm going to create another task for user details popup.

**Comment by mubarakshow** [comment]
@ArnasDickus yes, please do that and tag it as urgent.

**Pull request merged**
