### PR TITLE
change of the background. 

### PR DESCRIPTION
**Pull request by Melissendra**
image change. And trying to make it responsive.
map remove
Can you see to it, please and tell me if it's good enough or if i need to work on the background again?
thank you.

### CODE REVIEW

**Comment by M-AlNoaimi** [comment]
Hi, @Melissendra the code failed Travis' checks because of this specific error, please fix it and commit. Please tag me here once you have. 

>  ./src/App.js
>   Line 3:  'Navbar' is defined but never used  no-unused-vars

**Comment by sciortinomrc** [comment]
./src/App.js
  Line 6:  'Home' is defined but never used  no-unused-vars
Travis' check failed for this reason. It all looks good otherwise.

**Review by ArnasDickus — COMMENTED** [review]
Alright, here's my review:
Why landing page and dashboard is divided in half? From my understanding if user logged in it shows Dashboard. If he logged out it shows landing page. 
landing page divided in 2

1. You need to remove .idea by deleting it, and committing file.

2. created bad gitignore file. It's .gitignore not gitignore. Also we already have .gitignore file in project root. You should add .idea/ in there.

Are you sure you commited all files? Because I'm not seeing the landing page you showed in picture on discord page?

**Comment by Melissendra** [comment]
I don’t understand why you have such a screen in mine it’s full screen each
one.
For gitignore and idea i’ll do it. I forgot to erase them.
And the last commit I did will show you the same thing as in the discord I
commit it today at 2pm. Which title is design finished.
Here is the link to my repo with my last commit: https://github.com/Melissendra/mappypals/tree/Front-End Maybe I did something
wrong with the pull request!
Thanks for your review.

BA6F7F1E-971A-4348-AD28-CCE9A1713B9C

**Comment by ArnasDickus** [comment]
@Melissendra still the same thing. Due to weirdness of this situation I wait for another admin to review it. Hey @sciortinomrc or @mubarakshow could you review this?

**Comment by Melissendra** [comment]
Sorry to be such an inconvenience....

**Comment by ArnasDickus** [comment]
@Melissendra Don't worry about it. For me personally this is very interesting. How can both of us view the same files. And see 2 different things? This kind of mystery is way more interesting than spending my Saturday mindlessly  playing video games.

**Comment by Melissendra** [comment]
Thank you. You’re kind. Video games can be fun! ;)

**Review by sciortinomrc — COMMENTED** [review]
Tested and ready to merge

**Pull request merged**
