### PR TITLE
Login restored

### PR DESCRIPTION
**Pull request by InteriorNature**
Ky has not been maintained for 2 yrs. Results were inconsistent with the same submission fields. It has been changed to basic fetch. 
1) if user exists in database, but hasn't clicked email link (which turns active to true), there should be an error
2) if password entered does not match database, there should be an error
3) if user is active, email in db, and user password is OK, there should be a redirect
4) if email not in db, there should be an error
The previous way User.findOne was called did not return user as the implementation suggested. I implemented a better way to catch errors.  However, in the backend, - jwt.sign is not async. PR is needed for that. When signing in with totally correct info - sometimes there is no redirect because token and userId are not passed.

### CODE REVIEW

**Comment by mubarakshow** [comment]
@InteriorNature I'm still not able to login, instead, I'm getting `Error: undefined`

Tested Account
Email: team.mappypals@gmail.com
Password: mappypalsadmin

So its either the account credentials are wrong (which should return a different error) or the login problem persists.

**Comment by InteriorNature** [comment]
@mubarakshow When that error message happens, it means the token and userId are not passing before the backend returns. Do you have a dev who can make it async today? I am not available until tomorrow. Issue is in the jwt.sign in usercontroller.js needs to be done asynchronously.

**Comment by ArnasDickus** [comment]
@InteriorNature  Because I approved PR approval, you need to resolve conflicts.

**Comment by InteriorNature** [comment]
@ArnasDickus For what its worth at this point, **both error and success states** are now working :-)

**Comment by mubarakshow** [comment]
@InteriorNature when i click on `create account`, I wasn't redirected, neither did I get a success message nor sent a confirmation link. 
I only knew i signed up successfully from the backend console and when i try to login, I get this error: `Error: Account not active. Did you use our emailed link?`

If this is the accepted behavior, i can approve the pr

**Comment by mubarakshow** [comment]
I'll be approving this PR because we won't be using this implementation moving forward. However, great job @InteriorNature 👍

**Pull request merged**
