### PR TITLE
Cleaned up validation processes

### PR DESCRIPTION
**Pull request by InteriorNature**
**In Signup.js**
1) left the initialization of "number" in case it is used elsewhere
2) took out the validation of inputs that are duplicate (automatic handlers in inputs) 
3) the only validation kept is password!=confirmPassword
4) used an "alert" for password error until we have a system wide error message handler
5) took out onSignIn which was a placeholder for this.handlesubmit - the merge did not replace it
6) Please note there is some duplicate error checking code in users.js which I did not touch
**In Login.js**
1) added required to fields
2) took out duplicate validation process
I am unable to connect to mongoosenetwork.

### CODE REVIEW

**Comment by sciortinomrc** [comment]
Very well done!! 
Just 2 questions:
1. are we doing registrations fields check on the backend? I think UX wise would be better to have the check in the frontend   (server/routes/users.js)

2. facebook sdk was present on App.js ... any reason why it's been added to Signup.js?

**Comment by ArnasDickus** [comment]
@InteriorNature If you unable to connect to mongoose network your IP address is probably not whitelisted. Search in discord chat credentials for database from nottoobright.
Login to using credentials https://www.mongodb.com/ 
Click security> IP Whitelist> Add IP Address.

**Comment by InteriorNature** [comment]
The integration work is lost by not following trello. I do not understand why Arnas password reset was merged before this work is merged. I created the password reset form (please use Trello to see who is working on assigned tasks). It was created after this commit, where I CONTINUED the making all FORMS unified and working together with Form.js.

**Comment by sciortinomrc** [comment]
My fault. I'll reverse the merge. Didn't realized you were working on this task

**Comment by ArnasDickus** [comment]
@InteriorNature @sciortinomrc Also partly my fault I mixed up Reset Password task and forgot password tasks on Trello.
https://trello.com/c/LTWTXI1d/76-create-reset-password-from-provided-mockups
https://trello.com/c/9jQkLisd/65-create-signup-page-from-provided-mockups

**Comment by ArnasDickus** [comment]
I'am not sure what to do with this request. First it needs to resolve conflicts @InteriorNature

**Comment by InteriorNature** [comment]
Hi Arnas, this one can be cancelled, because my later pull request has these changes, as well.

**Pull request closed without merging**
