### PR TITLE
Team Page redesign

### PR DESCRIPTION
**Pull request by mubarakshow**
Since the previous contributor has left this task to me, I'm resubmitting the PR as i've previously completed the task.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
I'am finally back to the project. Let's review it.

**Review by ArnasDickus — COMMENTED** [review]
So here's my review: 
Mockup is here https://trello.com/c/Ryn28omN/44-team-page-mockup

1) Background is not looking good. In mock-up there is no background image.
2) In design there was no Who We Are title. The title itself is kinda boring. If you going to have a title we need to be closer to design color instead of just black bold.
3) Roles should be closer to name also not bold in according to design.  
4) Clicking on links don't take me neither to google or LinkedIn. Is it just me? It takes to the our website with that link so http://localhost:3000/www.linkedin.com
5) Yash Puthran does not have a link
6) In order to click on the link Portfolio, LinkedIn I have to click on text instead of button itself.
7) Expecting to have some sort of hover when hovering on the button.
8) Button text is different than design.
9) Font-size for countries too small. Also against design.

On mobile:
1) Not responsive on mobile. 
Screenshot_20190512-220613

Grammatical errors: 
1) my Name is Arnas Dičkus. If you font does not allow the use of č. Just name it Dickus. Not Disckson.
2) Pretty sure Yash Putran is not living in Lithuania. He lives in India according to his GitHub
https://github.com/nottoobright

**Comment by ArnasDickus** [comment]
@mubarakshow There's a conflicting files. package-lock.json. Be careful before committing to your project. Check manually in the project if your proposed changes works. And npm install works.

**Comment by mubarakshow** [comment]
I closed this PR because I deleted my previous fork and re-forked this repo so this PR is now showing ```unknown repository```
git-unknown

**Pull request closed without merging**
