### PR TITLE
fixed friend invite form by changing block to flex

### PR DESCRIPTION
**Pull request by brettCole**
changed conditional style from `block` to `flex` in `AddFriendForm.js` 
added `justify-content: flex-end` to `AddFriendForm.css` to push form to bottom of screen

### CODE REVIEW

**Review by ArnasDickus — CHANGES_REQUESTED** [review]
Hello, @brettCole Unable to drag the map around in the highlighted area.

Also, when working on PR. It's a good idea from dev branch to create a separate branch and submit it here in order to be able to work on other tasks while this one is reviewed.
can't-drag

**Comment by brettCole** [comment]
The imported Login css file is adding `min-height: 100vh` that's why there is that bug

**Review by brettCole — COMMENTED** [review]
imported Login css file caused parent div of form to have a `min-height:100vh` 
changed parent div css with id to `min-height:0vh` allowing parent div to be size of form child div

**Review by ArnasDickus — APPROVED** [review]

**Comment by ArnasDickus** [comment]
I didn't find any more problems. Time to approve it.

**Pull request merged**
