### PR TITLE
Storing token+userId when user logged in successfully

### PR DESCRIPTION
**Pull request by belyas**
This PR is for [Trello card](https://trello.com/b/NRNHGG12/mappypals)

I'm storing retrieved token and userId in local storage database for later use, then I redirect the user to home page.

@nottoobright you can now protect your route by checking if the token is present or not and also check for the back end if the token has been expired, I think you need to implement the back end endpoint for your protected route anyway, you can use `isAuthenticated` middleware to protect your endpoint in the backend.

@ArnasDickus I think we need to use Redux/Redux-saga to manage the state as for now we can't tell if the user is logged in as a global state, also things look a bit messy for me, we can do much better than that.

@nottoobright Ah for checking if the token is existing or you need token/userId you can get them from importing `{ getLocalData }` from `utils/localStorage` file.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
Hello, so I see you still working on your dev branch. I will add a redux task. I will wait for @nottoobright take on this before approving.

**Comment by belyas** [comment]
What do you mean @ArnasDickus by 

> so I see you still working on your dev branch?

 I didn't get it, sorry

**Comment by ArnasDickus** [comment]
@belyas I was talking about [this conversation](https://trello.com/c/NRfFsGN3/1-friends-invitation) that you added pull request from the dev branch. And now you stuck because until the pull request is approved you can't work on another task. And can't visit dev original branch. For me, it's no problem. This is more inconvenience to you.

**Comment by ArnasDickus** [comment]
Since this is a small change. I decided to approve it without nottoobright review.

**Comment by belyas** [comment]
@ArnasDickus Ah I see, I thought as long as I don't have any other open PR its okay to directly work on dev branch, but yes you're right, it'd always be better to create a specific branch for the new work then merge later once it's done. All right, I'll do that with Redux one as it's a big move. Thanks :)

**Pull request merged**
