### PR TITLE
fix on pop up forms

### PR DESCRIPTION
**Pull request by sciortinomrc**
Major fix on pop up forms and map component

### CODE REVIEW

**Comment by ArnasDickus** [comment]
According to sciorinomrc or masci4 on discord regarding this pull request:
I came across a big issue generated by a merged pull request in the past. 
Someone had changed a few things in the AddNewFriend component and Map component messing up everything.
I've just restore an older working version of it and I am about to submit the pr
please in the future when merging PR check what the new functionalities are for and why those changes.
on a side note: all those issues we had on the click and add new pins are related to this PS
PR

**Comment by sciortinomrc** [comment]
-bug flagged by @mubarakshow: click on map made the application crash
-found issue: if map clicked too quickly on loading mapbox has not enough time to setup all the function and it fails to deliver response for promise chain
-fix: if statement on last step of promise chain

bug should be solved now

**Review by ArnasDickus — COMMENTED** [review]
After new commit application seems to be working fine. And bug is also gone https://trello.com/c/RLEOaZ22/23-map-bug

**Comment by mubarakshow** [comment]
After the latest commit, the app runs without crashing and all functionalities work as expected.

**Pull request merged**
