### PR TITLE
About page

### PR DESCRIPTION
**Pull request by mubarakshow**
1. Updated the about page to the latest design. 
2. Updated the contributors to include only active guys.
3. Added links for portfolio and LinkedIn. 
- these links are not redirecting externally, instead, they are routing as if the links are in our application.
- e.g. got to about page> click on any user's portfolio > we get localhost:3000/www.google.com 
--I'll open an issue about this and few other issues.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
I'm going to review it now.

**Comment by ArnasDickus** [comment]
We have a problem. There is a conflict of interest. You were working on about page. But this is Team Page. Team Page is currently in progress by this person. Your task supposed to be about. Explaining the project. Not the team page. So yea...

https://trello.com/c/4dKerGzE/83-create-team-page-from-provided-mockup

**Review by ArnasDickus — COMMENTED** [review]
You mixed up the tasks. This is supposed to be about page not Team Page. Team Page is already in progress. Since I can't approve task that already have assigned member. I'm forced to close this pull request.
https://trello.com/c/4dKerGzE/83-create-team-page-from-provided-mockup

**Comment by mubarakshow** [comment]
@ArnasDickus Ohh, but the about page is where we included the team, or did I miss something in the design? 
Do we have a mockup for the about page then? 

Thanks!

**Pull request closed without merging**
