### PR TITLE
Front end - forgot password form and form css synchronization

### PR DESCRIPTION
**Pull request by InteriorNature**
This is the additional work from yesterday that replaces the prior merge req by Arnas.

### CODE REVIEW

**Review by ArnasDickus — COMMENTED** [review]
Hello, so this seems to be working well.
Login: Designed and functional
Sign Up: Designed and functional
I forgot my password: Designed not functional

Before approving you need to rename ResetPassword.js and ResetPassword.css to ForgotPassword.js and ForgotPassword.css. Because this is Forgot password page. Not reset password page. Reset Password  page is waiting for approval here https://github.com/zero-to-mastery/mappypals/pull/53

**Comment by InteriorNature** [comment]
Ok. My machine will not boot! I'll see what I can do.

**Comment by InteriorNature** [comment]
Reset.js was renamed ForgotPassword.js. It already works with form.css and login.css. There is no reset.css to rename. I used git add and git commit --amend

**Comment by ArnasDickus** [comment]
@InteriorNature are you sure that you committed changes in here. Because if I click on file changes. I see ResetPassword.css and ResetPassword.js?

ResetPassword css and ResetPassword js

**Comment by InteriorNature** [comment]
What I am saying is that when @sciortinomrc unmerged a later pull request, something collapsed. My files in this pull request disappeared. These are not my files! This is not what was in this pull request.

**Comment by sciortinomrc** [comment]
My revert had been closed without merge.. I think it might still be related to the double PR for the same task

**Comment by sciortinomrc** [comment]
Closing as the new commit with the correct file are not showing here.
Please Make another pull request into the correct branch

**Pull request closed without merging**
