### PR TITLE
Layout navbar changes

### PR DESCRIPTION
**Pull request by Nilkamal**

### CODE REVIEW

**Comment by sciortinomrc** [comment]
I have not checked the code yet but could you please make a PR on the right branch? We are not merging PR on master

**Comment by ArnasDickus** [comment]
@sciortinomrc The statement We are not merging PR on master is false. Because of poor github branching instructions. We still merge everything to master.

**Comment by ArnasDickus** [comment]
So I looked at your code, and it seems not much changed. So I just going to paste my old review.

Good work for adding a pull request. Navbar is starting to look good. Here's the problems I encountered. Also I added optional tasks if you up to it.
Okay I see a 2 problems and 3 improvements.

Your navbar don't have mobile menu. As you shrinking the view the hamburger button should appear. And menu be hidden. If I click on hamburger menu should appear from right side. To know exact size when menu should appear try to make it look good on login page.
menu-with-navbar

header now stands at his own element. Navbar should be on right side with the element, login menu should be next to navbar not below.
menu-with-navbar

horizontal lines should look closer to design.

Login and sign up page buttons should look closer to design Look at login.js button design.

After Team members there should be a new line look in design.

Apart from that good work. Started with not the easiest task.

**Comment by sciortinomrc** [comment]
Code reviewed also by me, found same issues. Waiting for corrections

**Comment by ArnasDickus** [comment]
@sciortinomrc I think next time we should add a person to be a reviewer. So that both us won't review the same code.

**Pull request closed without merging**
