### PR TITLE
Major release

### PR DESCRIPTION
**Pull request by sciortinomrc**
Add edit friend details, Add FB api, few fix on css and js
Add server folder and files

### CODE REVIEW

**Comment by ArnasDickus** [comment]
Hi, I have a few questions about this update

1) Is your discord name masci4? If not what is your discord account name?
2) You added  package.json file and server.js in server folder. So in order for me to launch project in development you need write npm install twice. One in main folder, and one in server folder. To start live server still from main folder directory is this correct?
3) Could you explain in more details, about adding FB api? And what is the idea behind it?

**Comment by sciortinomrc** [comment]
Hey
1. Yes, that's me.
2. I've created the server folder here to avoid a second repo as I believe they should be separated. 
You will have to treat them as two different repos so init both and npm start both from their own root. 
3. Fb api is to get the fb login working as we had decided to go for it although I do not know whether anything has changed

**Comment by ArnasDickus** [comment]
Well congrats on finishing such a major update. However my main concern here. Is that your pull request is huge and modifies multiple features. I think in the future it would be better to create multiply pull requests ideally ratio 1 task 1 pull request. What do you think?

Your added features that I think could have been divided into multiple pull requests
1) Added server folder
2) Added fbi Api
3) Css fixes.
4) Edited friend details.

**Comment by ArnasDickus** [comment]
Hello again sciortinomrc, are you aware that running npm run start from server folder would give an error?
launching server error

**Comment by sciortinomrc** [comment]
Hey Arnas,
Well spotted.. It looks like the file got deleted fron my folder.. I'll check previous version when I am home

**Comment by sciortinomrc** [comment]
As I suspected it got overwritten during a pull operation but I could restore it from previous commits

**Pull request merged**
