### PR TITLE
drag-and-drop icon and function added

### PR DESCRIPTION
**Pull request by InteriorNature**
1) Icon replaced for dropped pin (had to be converted from svg to png)
2) Drag-and-drop functionality added. 
3) Mapbox has incorporated screen reader capabilities with iOS, and no further aria-live functions are supposedly necessary for map functions. 
4) The draggable property for react-map-gl creates a warning message in the console, but the usability does not appear an issue.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
Hello @InteriorNature you need to resolve conflicts first before I can review your pull request. 
Word of warning before clicking mark as resolve copy the code you just resolved and paste it into your application to make sure that you haven't accidentally broke the application.

**Comment by InteriorNature** [comment]
@ArnasDickus apprarently I had not merged the Prettier changes. I also had started to refactor the render, but decided to revert that. All good now.

**Comment by mubarakshow** [comment]
Hi, @InteriorNature, i'm unable to drag the pins. Not sure why...

**Comment by mubarakshow** [comment]
@InteriorNature, ok the pins are draggable before pinning them to the map. They're undraggable after being pinned.

**Comment by InteriorNature** [comment]
@muburakshow I have the opposite. I drop a pin, and then I can drag and drop it. What browser and type of device are you using? I am using chrome and firefox. Did you use touch or a mouse?

**Comment by mubarakshow** [comment]
@InteriorNature I tested it on Chrome and Firefox and got the same behavior

**Comment by InteriorNature** [comment]
@mubarakshow   Do you mean after you submit the form? And the pin then is fixed in place? Right now, the form pops up after a settimeout - not with onDragEnd. Arnas is making the invite form. The logic of how the form pops up will change.

**Comment by mubarakshow** [comment]
@InteriorNature i mean, I'm able to drag the pin after the form pops up waiting to be filled. As soon as i click the "add friend" button, the pin drops on the spot and becomes undraggable. 

Is this the same behavior on your end?

**Comment by InteriorNature** [comment]
Yes. Do you want all pins to be draggable after the friend is added? I thought when a friend accepts their invitation, there are automatic updates to lat/long or zipcode that moves the pin?

**Comment by mubarakshow** [comment]
@InteriorNature  We can keep it this way for now. Our users' interactions with the map will tell us what to do next. This is fine for now.

**Comment by ArnasDickus** [comment]
So since @mubarakshow approved this pull request. I'am going to merge it.

**Pull request merged**
