### PR TITLE
Signup & Login forms match mockups

### PR DESCRIPTION
**Pull request by InteriorNature**
Login and Signup Forms styles are synchronized. Backend connection - axios calls can be added now.

### CODE REVIEW

**Comment by ArnasDickus** [comment]
I will  review it. Congrats on putting it into front-end branch.

**Comment by ArnasDickus** [comment]
Hello good work, @InteriorNature the task look pretty well done. I only found 3 bugs.

Looking at my phone. I forgot my password should be farther apart from login button.
Screenshot_20190422-162633
Login page on my phone allows me to scroll in x direction 
Sign up page on my phone allows me to scroll in x direction. You can try to apply overflow-x: hidden

Anyways if you fix these minor bugs I would approved it.
Also if you going to try to view it using your phone. I suggest comment it out window.FB.init on Signup and Login.js pages. So that you won't get errors when watching on mobile.

**Comment by ArnasDickus** [comment]
Hi, so I attempted to fix branch conflicts. But now test failing. You need to change one line here.
In signup.js
```
import Form from './Form.js';  change to the line below, for Travis test to work.
import Form, { PasswordReqs } from "./Form.js";
```

**Comment by InteriorNature** [comment]
Hi Arnas - The new changes are more mobile-friendly. A note about the facebook login button - it does not center in mobile. I tried many suggested approaches. It appears the widget centers and the iframe centers. The image itself will not center within the iframe. I believe this is on facebook's end. I tried the other sizes they offer, as well.

**Comment by ArnasDickus** [comment]
Alright, if we find a way to fix it we can improve it later.

**Pull request merged**
